### ISSUE TITLE
Why after-compile ?

### ISSUE THREAD

**Issue by nabiltntn** [Fridus/webpack-watch-files-plugin#1]
https://github.com/Fridus/webpack-watch-files-plugin/blob/2cf20516a795173466e16261b336e422e4b68b4a/src/index.js#L23

Why did you define the plugin at `after-compile` ?
why not 'compile' ?

**Comment by Fridus** [comment]
Hi,
Because I add the files on the dependencies of the compilation.
At `compile`, the dependencies does not exists yet.
