### ISSUE TITLE
does not work with webpack 4 ?

### ISSUE THREAD

**Issue by devmondo** [Fridus/webpack-watch-files-plugin#6]
hi,

i tried this     
`new WatchExternalFilesPlugin({files: ["./src/**/*.ts"]})` 
and this 
`new WatchExternalFilesPlugin({files: ["./src**"]})`

but none of them work, when i change my files webpack dosnt kick bundling.

thanks in adavanced.

**Comment by Fridus** [comment]
Hi, 

Show me your `webpack.config.js`

Ex:
```js
import WatchExternalFilesPlugin from 'webpack-watch-files-plugin'
let config = {
  // ...
  plugins: [
    new WatchExternalFilesPlugin({
      files: [
        './src/**/*.ts'
      ],
      verbose: true
    })
  ]
}
```

Try `verbose: true`

**Comment by devmondo** [comment]
thanks for reply, 

with verbose it indeed shows files are added to watch 

Additional files watched :  [
"C:/project-a/src/a.ts",
"C:/project-a/src/b.ts",
"C:/project-a/src/index.ts"
]

but again, when i edit `b.ts` which is not referenced anywhere in my entry (which is the purpose of using this plugin :) ) it does not force to kick webpack compilation.

also another problem is that it does not watch files or folders added later ( maybe i am wrong) 

my config

```js
module.exports = {
    mode: "development",
    watch: true,
    stats: "normal",
    devtool: "inline-source-map",
    entry: {
        "app": "./src/index.ts"
    },
       plugins: [
        new CleanWebpackPlugin(["dist"]),
        new EventHooksPlugin({
            "done": () => {
                fsExtra.copySync(bundleSource, bundleDist);
                process.stdout.write(`bundling finished`);
            }
        }),
        new FriendlyErrorsWebpackPlugin({
            compilationSuccessInfo: {
                messages: [""],
                notes: ["Finished Bundling"]
            }
        }),
        new WatchExternalFilesPlugin({files: [`./src/**/*.ts`], verbose: true})
       
    ],
    output: {
        path: path.join(__dirname, "dist"),
        publicPath: "./",
        filename: "[name].js",
        chunkFilename: "[name].chunk.js"
    },
    resolve: {
        modules: ["node_modules", "C:/api/node_modules"],
        extensions: [".ts", ".tsx", ".js"]
    },
    module: {
        rules: [
            {
                test: /\.(html)$/,
                use: {
                    loader: "html-loader",
                    options: {
                        attrs: false
                    }
                }
            },
            {
                test: /\.(s*)css$/,
                use: [{loader: "style-loader"}, {loader: "css-loader", options: {url: false}}, {loader: "sass-loader"}]
            },
            {
                test: /\.tsx?$/, loader: "ts-loader",
                include: path.join(__dirname, "src"),
                options: {
                    transpileOnly: true,
                    silent: true
                }
            }
        ]
    }
};
```

**Comment by Fridus** [comment]
If your file is in the array of files found, a new compilation will be triggered on save in this file. Webpack run this compilation it-self.
Tested on mac os X & Linux with webpack 3 & 4.

What's your version of webpack & this plugin ?

**Comment by devmondo** [comment]
this is precisely what i am expecting :)  but it is not happening, i am on windows 10 by the way

webpack version 4.6.0
webpack watch files plugin version 1.0.2

**Comment by Fridus** [comment]
I tested on Mac OS & Windows. It works but not on Windows when the files match ... 🤔

**Comment by devmondo** [comment]
oh, now i understand what you mean, you mean you replicated the issue

**Comment by ChrisBAshton** [comment]
Same issue reported with Webpack v4 in a similar plugin: https://github.com/sap9433/filewatcher-webpack-plugin/issues/7

**Comment by Fridus** [comment]
https://travis-ci.org/Fridus/webpack-watch-files-plugin/builds/373990982

- Linux
  + Webpack 3 : ✅
  + Webpack 4 : ✅
- Mac OS
  + Webpack 3 : ✅
  + Webpack 4 : ✅
- Windows
  + Webpack 3 : ❓
  + Webpack 4 : ❌

I think this bug come from Webpack on Windows...

**Comment by Fridus** [comment]
Please, test the new version `1.0.3` :)
