### ISSUE TITLE
TypeError: WatchExternalFilesPlugin is not a constructor

### ISSUE THREAD

**Issue by mcmc4519** [Fridus/webpack-watch-files-plugin#7]
windows 8, x64
webpack 4
 **webpack.config.js**

```
const WatchExternalFilesPlugin = require('webpack-watch-files-plugin');

{
//webpack configs
plugins: [
    new WatchExternalFilesPlugin({
      files: ['./path_to_files/*.html'],
      verbose: true,
    }),
  ],
}
```

**Comment by Fridus** [comment]
https://github.com/Fridus/webpack-watch-files-plugin/issues/2

Try `const WebpackWatchPlugin = require('webpack-watch-files-plugin').default;`

⚠️ Webpack watching on Windows seems to be buggy : https://github.com/Fridus/webpack-watch-files-plugin/issues/6
